
server:
  port: 8089

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbpedido
    username: postgres
    password: 12345678
    tomcat:
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
     
   
   
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 2
      minimum-idle: 1
      initialization-fail-timeout: 2000
      isolate-internal-queries: true
      validation-timeout: 3000
  jpa:
    database: POSTGRESQL
    open-in-view: true
    hibernate:
      ddl-auto: 'none '
    properties:
      hibernate:
        
        #dialect: org.hibernate.dialect.PostgreSQL9Dialect
       
  main:
    allow-circular-references: true
  sql:
    init:
      platform: postgres
      

